name: Keep Alive
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
